#!/usr/bin/env python3
"""
graphic_figure.py - PowerPoint panel art inside a figure folder.

Some figure panels are not plots. A reaction scheme, an apparatus diagram, a
mechanism, a sample-preparation flow - nobody draws those in ggplot, and the
honest answer is not a drawing API but the editing surface people already
have. So a graphic panel is ONE PowerPoint slide, authored by you, rendered to
.png at the journal's pixel size, and composed into the figure by the same
script that draws the plotted panels beside it.

The layout, inside a float folder that tools/scaffold.py already made:

    plan/figures/Fig02/
        panels.R              GENERATED - renders every *_source.pptx
        figure.R              yours - composes the panels into the figure
        panelA_source.pptx    YOURS - open it in PowerPoint
        panelA_source.png     GENERATED
        .render_state.json    GENERATED - the SHA-256 that answers "stale?"
        figure.png/.pdf       GENERATED by save_float()

A whole-figure graphic (no panels at all) is `figure_source.pptx` instead.

The .pptx is written ONCE and never overwritten. It is the file you edit, and
an engine that regenerates it would throw away the work every time it ran.

Nothing here has to know whether the other panels are graphics. `image_panel()`
draws a dashed placeholder for art that does not exist yet, and a plotted panel
is an ordinary ggplot - so a figure can mix them freely, and can start as all
placeholders while the data is still being collected.

Usage:
  python graphic_figure.py status "path/to/Project"
  python graphic_figure.py add "path/to/Project" --figure 2 --panel A
  python graphic_figure.py add "path/to/Project" --figure 2          # whole figure
  python graphic_figure.py render "path/to/Project" [--figure 2] [--force]
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import subprocess
import sys

for _stream in (sys.stdout, sys.stderr):
    # A redirected stream (a pipe, a StringIO under a harness) has no
    # reconfigure at all; asking for it by name keeps that case quiet.
    _reconfigure = getattr(_stream, "reconfigure", None)
    if _reconfigure is not None:
        try:
            _reconfigure(encoding="utf-8", errors="replace")
        except ValueError:
            pass

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_DIR = os.path.join(HERE, "project_template")
STATE_FILE = ".render_state.json"
PANELS_SCRIPT = "panels.R"


def _load(name: str, filename: str):
    """Import a sibling engine by path under a distinct module name.

    tools/ and tests/ carry same-named files, so a plain import resolves to
    whichever directory is first on sys.path. Every suite in this toolkit
    loads its engine this way; doing the same here keeps `graphic_figure.py`
    importable from a test that is also called graphic_figure.py.
    """
    spec = importlib.util.spec_from_file_location(name,
                                                  os.path.join(HERE, filename))
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {filename}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# The float folder grammar and the .pptx writer both already exist. Reusing
# them is the point: a second copy of either is the copy nobody re-reads.
_scaffold = _load("_gf_scaffold", "scaffold.py")
_toc = _load("_gf_toc", "toc_graphic.py")

list_float_dirs = _scaffold.list_float_dirs
parse_float_dir = _scaffold.parse_float_dir

PANEL_RE = re.compile(r"^panel([A-Z])_source\.pptx$")
WHOLE_RE = re.compile(r"^figure_source\.pptx$")
SOURCE_RE = re.compile(r"^(?:panel[A-Z]|figure)_source\.pptx$")


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------
# A graphic panel's absolute size matters less than it looks: image_panel()
# preserves the .png's aspect ratio and fits it into whatever slot patchwork
# gives it. What the size DOES decide is how many pixels the panel has, and a
# panel authored at 1.6 in and printed at 3.3 in is soft in exactly the way a
# reviewer notices. So the default is a full single column, and the shape is
# the dial worth turning.

WIDTHS = {"single": 3.33, "double": 7.0, "half": 1.65}
DEFAULT_ASPECT = 0.75

# THE PIXEL COUNT IS NOT DECIDED HERE. plan/theme/render_pptx.R multiplies the
# slide's inches by DPI, and DPI comes from theme_journal.R's preset table as
# overridden by a sourced plan/theme/journal_target.yml - a resolution this
# engine cannot reproduce, because a journal_target.yml written from the
# journal's own guidelines beats any table shipped in Python.
#
# So a dpi table here would be a second copy that disagrees with the first, and
# it did: `add` reported 999 x 749 px for a panel that rendered at 1998 x 1499.
# What this engine fixes is the slide's INCHES, which is what decides the
# aspect ratio; `status` reports the pixel size the render actually produced,
# read back out of .render_state.json rather than predicted.


def read_project_yml(root: str) -> dict:
    return _scaffold.read_project_yml(root)


def panel_spec(root: str, width: str = "single",
               aspect: float = DEFAULT_ASPECT) -> dict:
    """The spec toc_graphic.write_pptx() wants, for a figure panel."""
    try:
        w = float(width)
    except (TypeError, ValueError):
        w = WIDTHS.get(str(width).lower(), WIDTHS["single"])
    return {"term": "figure panel", "width_in": round(w, 3),
            "height_in": round(w * float(aspect), 3),
            "font_family": "Arial", "font_preferred_pt": 8, "font_min_pt": 6}


# ---------------------------------------------------------------------------
# Locating a float and its sources
# ---------------------------------------------------------------------------

def find_float(root: str, number: int, supplementary: bool = False,
               kind: str = "figure") -> dict | None:
    for f in list_float_dirs(root):
        if (f["kind"] == kind and f["n"] == number
                and f["supplementary"] == supplementary):
            return f
    return None


def sources_in(path: str) -> list[str]:
    """Every panel source in a float folder, in panel order.

    PowerPoint writes ~$name.pptx beside a file it has open; that lock stub is
    not a source, and rendering it produces a blank slide rather than an error
    - which is the worst of the three outcomes, because a blank panel looks
    like a panel.
    """
    try:
        names = sorted(os.listdir(path))
    except OSError:
        return []
    return [n for n in names
            if SOURCE_RE.match(n) and not n.startswith("~$")]


def panel_letter(source: str) -> str:
    m = PANEL_RE.match(source)
    return m.group(1) if m else ""


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    try:
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                h.update(chunk)
    except OSError:
        return ""
    return h.hexdigest()


def read_state(path: str) -> dict:
    try:
        with open(os.path.join(path, STATE_FILE), "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return {}


def source_state(float_path: str, source: str) -> dict:
    """Is this source's .png current? Answered by content, never by mtime.

    OneDrive rewrites modification times on sync, so an mtime comparison both
    re-renders files nobody touched and can call a file current after a sync
    has replaced it. The digest is the same one plan/theme/render_pptx.R
    writes, so the R side and this side cannot disagree about what is stale.
    """
    pptx = os.path.join(float_path, source)
    png = os.path.join(float_path, source[:-5] + ".png")
    rec = read_state(float_path).get(source, {})
    have = os.path.isfile(png)
    digest = _sha256(pptx)
    return {"source": source, "panel": panel_letter(source),
            "pptx": pptx, "png": png, "rendered": have,
            "stale": (not have) or rec.get("sha256") != digest,
            "backend": rec.get("backend", ""),
            "px": rec.get("px", [])}


# ---------------------------------------------------------------------------
# panels.R
# ---------------------------------------------------------------------------

PANELS_R = '''# {folder}/panels.R
# --- drawn float (create-graphic-figure) ---
# GENERATED by tools/graphic_figure.py. Safe to re-generate; safe to edit.
#
# The marker above records that this float's art is DRAWN rather than
# plotted, where a later round can read it: `scaffold.py float lint` reports
# a float marked drawn that holds no PowerPoint source, because that is a
# picture nobody but an R programmer can change (item 82). Repeated here
# rather than imported - every engine in this toolkit is standalone - and
# pinned against scaffold.py's own constant by tests/graphic_figure.py.
#
# Renders every *_source.pptx in this folder to a .png beside it, at the
# journal's pixel size. Unchanged sources are skipped - a SHA-256 of the
# .pptx answers "is the render stale", never the modification time, because
# OneDrive rewrites mtimes on sync.
#
# plan/render_all.R runs this BEFORE figure.R. That ordering is the whole
# reason the file is separate: the panel art has to exist before the script
# that composes it reads it, and "sorted order" alone would put figure.R
# first. See render_all.R's LAST_IN_FOLDER.
#
# You do not run this by hand. `Rscript plan/render_all.R` is still the only
# command. To force a re-render of everything here:
#     render_panel_sources(force = TRUE)

source(here::here("plan", "setup.R"))

render_panel_sources()
'''


def write_panels_script(float_path: str) -> str:
    path = os.path.join(float_path, PANELS_SCRIPT)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(PANELS_R.format(folder=os.path.basename(float_path)))
    return path


# ---------------------------------------------------------------------------
# figure.R
# ---------------------------------------------------------------------------

def compose_line(source: str) -> str:
    """The line that puts this panel's art into figure.R.

    graphic_panel() rather than image_panel() for the reason helpers.R gives:
    an aspect-locked image ignores the height patchwork hands it, so a title
    drawn inside the panel floats over whatever is beside it. Measured - two
    graphic panels side by side came out titled "Reaction sccAhpepmaeratus".
    """
    letter = panel_letter(source)
    stem = source[:-5]
    if not letter:
        return f'p <- graphic_panel("{stem}.png")'
    return (f'p_{letter.lower()} <- graphic_panel("{stem}.png",\n'
            f'                      title = "[TK: short panel title]", '
            f'tag = "{letter}")')


STARTER_FIGURE_R = '''# {folder}/figure.R
#
# A figure with PowerPoint panel art in it. panels.R has already turned every
# *_source.pptx in this folder into a .png by the time this runs - that is
# what render_all.R's ordering rule is for.
#
# Panels do not all have to be graphics. image_panel() draws a dashed grey
# placeholder when its .png is not there yet, and a plotted panel is an
# ordinary ggplot, so this figure renders from the first day and fills in as
# the art and the data arrive.

source(here::here("plan", "setup.R"))

# --- graphic panels ---------------------------------------------------------
{graphics}

# --- plotted panels ---------------------------------------------------------
# d <- load_data("data/raw/<file>.csv")
# p_{next_letter_lower} <- panel_title(
#   ggplot(d, aes(x = <x>, y = <y>)) + geom_point(size = 1.6) +
#     labs(x = "<x label>", y = "<y label>"),
#   title = "[TK: short panel title]", tag = "{next_letter}")

# --- composition ------------------------------------------------------------
# patchwork: `|` side by side, `/` stacked, and `(a | b) / c` for two rows.
#
# State `height =` as soon as the layout is more than one row. save_float()
# derives a height from the panel COUNT, which assumes a single row - three
# panels arranged (A | B) / C come out at the height of one row and the
# graphic panels shrink to nothing in the middle of it.
{compose}
'''


def is_pristine_slot(float_path: str, script: str) -> bool:
    """Is this float folder still exactly what the scaffold put there?

    True only when it holds that one script and the script is byte-identical
    to the template. Anything else means somebody has worked in here, and a
    generator that rewrites their figure.R has destroyed the work it was
    called to help with.
    """
    try:
        contents = os.listdir(float_path)
    except OSError:
        return False
    if contents != [script]:
        return False
    sub = "figures" if script == "figure.R" else "tables"
    tmpl = os.path.join(TEMPLATE_DIR, "plan", sub, "_template", script)
    try:
        with open(os.path.join(float_path, script), encoding="utf-8") as a, \
                open(tmpl, encoding="utf-8") as b:
            return a.read() == b.read()
    except OSError:
        return False


def starter_figure(float_path: str, sources: list[str]) -> str:
    letters = [panel_letter(s) for s in sources if panel_letter(s)]
    nxt = chr(ord(max(letters)) + 1) if letters else "B"
    graphics = "\n".join(compose_line(s) for s in sources) or "# (none yet)"
    if letters:
        compose = ("p <- " + " | ".join(f"p_{l.lower()}" for l in letters)
                   + "\nsave_float(p)")
    else:
        compose = "save_float(p)"
    return STARTER_FIGURE_R.format(
        folder=os.path.basename(float_path), graphics=graphics,
        compose=compose, next_letter=nxt, next_letter_lower=nxt.lower())


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def status(root: str) -> dict:
    floats = []
    for f in list_float_dirs(root):
        srcs = sources_in(f["path"])
        if not srcs:
            continue
        floats.append({
            "label": f["label"], "dir": f["rel"],
            "has_panels_script": os.path.isfile(
                os.path.join(f["path"], PANELS_SCRIPT)),
            "sources": [source_state(f["path"], s) for s in srcs]})
    return {"path": os.path.abspath(root), "floats": floats,
            "backend": detect_backend(),
            "stale": sum(1 for fl in floats for s in fl["sources"]
                         if s["stale"])}


def detect_backend() -> str:
    """Which renderer this machine actually has, checked rather than assumed."""
    import glob
    if glob.glob("C:/Program Files/Microsoft Office/root/Office*/POWERPNT.EXE") \
            or glob.glob("C:/Program Files (x86)/Microsoft Office/root/"
                         "Office*/POWERPNT.EXE") \
            or glob.glob("C:/Program Files/Microsoft Office/Office*/POWERPNT.EXE"):
        return "powerpoint-com"
    for c in ("C:/Program Files/LibreOffice/program/soffice.exe",
              "/usr/bin/soffice", "/usr/local/bin/soffice",
              "/Applications/LibreOffice.app/Contents/MacOS/soffice"):
        if os.path.exists(c):
            return "libreoffice"
    return ""


def add(root: str, number: int, panel: str = "", width: str = "single",
        aspect: float = DEFAULT_ASPECT, supplementary: bool = False,
        dry_run: bool = False) -> dict:
    """Add one PowerPoint panel source to a figure folder."""
    fl = find_float(root, number, supplementary)
    if fl is None:
        return {"error": f"no Figure {'S' if supplementary else ''}{number} in "
                         f"plan/figures/ - make one first with:\n"
                         f"  python tools/scaffold.py float new <project> --figure"
                         f"{' --supplementary' if supplementary else ''}"}

    panel = (panel or "").strip().upper()
    if panel and not re.fullmatch(r"[A-Z]", panel):
        return {"error": f"panel must be a single letter A-Z, not {panel!r}"}
    source = f"panel{panel}_source.pptx" if panel else "figure_source.pptx"
    existing = sources_in(fl["path"])

    # A whole-figure graphic and lettered panels are different shapes of
    # figure, and a folder holding both renders one of them into nothing.
    if panel and "figure_source.pptx" in existing:
        return {"error": f"{fl['rel']} already has a whole-figure "
                         f"figure_source.pptx. Rename it to panelA_source.pptx "
                         f"first if this figure is becoming multi-panel."}
    if not panel and any(PANEL_RE.match(e) for e in existing):
        return {"error": f"{fl['rel']} already has lettered panels "
                         f"({', '.join(existing)}). Pass --panel to add another."}

    target = os.path.join(fl["path"], source)
    if os.path.exists(target):
        # The .pptx is the editing surface. Regenerating it would throw away
        # the drawing, which is the only thing in the folder nothing else can
        # reproduce.
        return {"error": f"{fl['rel']}/{source} already exists, and it is "
                         f"yours - this never overwrites one. Open it in "
                         f"PowerPoint, or delete it first to start over."}

    spec = panel_spec(root, width, aspect)
    suggestion = {
        "title": "[TK: what this panel shows]",
        "stages": [
            {"label": "[TK: starting point]", "caption": ""},
            {"label": "[TK: what happens]", "caption": ""},
        ],
        "footnote": "",
    }
    # Asked BEFORE anything is written into the folder: is_pristine_slot()
    # answers "does this folder hold only the untouched template", and writing
    # panels.R first makes the answer permanently no. That is how a generator
    # ends up never writing the starter figure.R it exists to write.
    pristine = is_pristine_slot(fl["path"], "figure.R")

    written = {"shapes": 0}
    if not dry_run:
        written = _toc.write_pptx(target, spec, suggestion)
        write_panels_script(fl["path"])

    figure_r = os.path.join(fl["path"], "figure.R")
    sources_after = sorted(set(existing) | {source})
    if pristine and not dry_run:
        with open(figure_r, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(starter_figure(fl["path"], sources_after))

    return {"path": os.path.abspath(root), "label": fl["label"],
            "dir": fl["rel"], "source": source,
            "pptx": f"{fl['rel']}/{source}",
            "png": f"{fl['rel']}/{source[:-5]}.png",
            "panels_script": f"{fl['rel']}/{PANELS_SCRIPT}",
            "figure_written": pristine,
            "compose_line": compose_line(source),
            "width_in": spec["width_in"], "height_in": spec["height_in"],
            "shapes": written.get("shapes", 0), "dry_run": dry_run}


def _rscript() -> str | None:
    return _toc._rscript()


# ---------------------------------------------------------------------------
# Geometry - does the drawing collide with itself? (item 103)
# ---------------------------------------------------------------------------
#
# A drawn float is authored as a PowerPoint slide and rendered to an image,
# and nothing anywhere checked that the slide's own elements do not collide.
# A leader line running from a marker to its label can pass straight through a
# DIFFERENT label's text, and two labels can sit on top of each other, and the
# render still succeeds: the .png is written, the staleness record is written,
# the float is composed into the manuscript, and no command reports anything.
#
# Measured: Figure 1 of a real review drew two cytoplasmic-tail leader lines
# straight through the words S-palmitoylation and ubiquitination, so both
# labels had a vertical rule through the middle of them. It rendered, embedded
# at the right size and shipped with no complaint. The user caught it by
# looking at the picture - which is exactly the reading that gets skipped once
# a figure has been carried unchanged through a round or two.
#
# So legibility of a drawn float was asserted by nobody, while every other
# property of it was machine-checked. This is the check, and it lives where
# the float is PRODUCED rather than with a later reader of the .png, because
# it needs the label boxes and the line endpoints and the .png has only
# pixels.
#
# **A leader line is SUPPOSED to touch its own label.** That is the false
# positive that would make this check worthless, and it is why the rule is
# not "no line touches any label". A line's own labels are the ones its two
# endpoints land in or beside; a crossing is the line passing through some
# OTHER label. That is the shape of the real defect and it is the shape this
# tests for.

# python-pptx, and it may not be installed. Absent, this reports DID NOT RUN
# and says so out loud - it never reports a clean slide it did not read. A
# check that cannot run and stays quiet is worse than no check, because the
# silence is indistinguishable from a pass (items 80 and 114).
EMU_PER_INCH = 914400

# A label's ink does not reach the edge of its text frame, and a leader line
# is routinely drawn to stop just inside it. Both boxes are shrunk towards
# their centres before anything is compared, so touching an edge is not a
# collision and crossing the middle of a word is.
INK_MARGIN = 0.18

# Two labels overlapping by less than this fraction of the smaller one is
# kerning, not a collision.
OVERLAP_TOLERANCE = 0.06


def _shrink(box: tuple, frac: float = INK_MARGIN) -> tuple:
    x0, y0, x1, y1 = box
    dx, dy = (x1 - x0) * frac, (y1 - y0) * frac
    return (x0 + dx, y0 + dy, x1 - dx, y1 - dy)


def _seg_hits_box(p0: tuple, p1: tuple, box: tuple) -> bool:
    """Liang-Barsky: does the segment p0->p1 enter this rectangle?"""
    x0, y0 = p0
    x1, y1 = p1
    bx0, by0, bx1, by1 = box
    dx, dy = x1 - x0, y1 - y0
    t0, t1 = 0.0, 1.0
    for p, q in ((-dx, x0 - bx0), (dx, bx1 - x0),
                 (-dy, y0 - by0), (dy, by1 - y0)):
        if p == 0:
            if q < 0:
                return False
            continue
        r = q / p
        if p < 0:
            if r > t1:
                return False
            t0 = max(t0, r)
        else:
            if r < t0:
                return False
            t1 = min(t1, r)
    return t0 <= t1


def _overlap_fraction(a: tuple, b: tuple) -> float:
    ax0, ay0, ax1, ay1 = a
    bx0, by0, bx1, by1 = b
    w = min(ax1, bx1) - max(ax0, bx0)
    h = min(ay1, by1) - max(ay0, by0)
    if w <= 0 or h <= 0:
        return 0.0
    smaller = min((ax1 - ax0) * (ay1 - ay0), (bx1 - bx0) * (by1 - by0))
    return (w * h) / smaller if smaller else 0.0


def _slide_elements(path: str) -> dict:
    """Every label box and every line segment on the first slide.

    Returns `{"labels": [...], "lines": [...]}` or raises. A shape is a LABEL
    when it carries text and a LINE when it does not and is a connector or a
    straight-line autoshape. Anything else - a picture, a filled block, a
    shape with neither - is neither, and is ignored rather than guessed at.
    """
    from pptx import Presentation                      # noqa: PLC0415

    prs = Presentation(path)
    slide = prs.slides[0]
    labels, lines = [], []
    for sh in slide.shapes:
        try:
            left, top = int(sh.left or 0), int(sh.top or 0)
            wid, hgt = int(sh.width or 0), int(sh.height or 0)
        except (TypeError, ValueError):
            continue
        # Asked through getattr in both halves. `has_text_frame` is False on
        # a picture or a connector and `text_frame` does not exist on the
        # base shape at all, so reaching for the attribute directly is an
        # AttributeError on exactly the shapes this walks past.
        text = ""
        frame = getattr(sh, "text_frame", None) \
            if getattr(sh, "has_text_frame", False) else None
        if frame is not None:
            text = (getattr(frame, "text", "") or "").strip()
        box = (float(left), float(top), float(left + wid), float(top + hgt))
        if text:
            labels.append({"name": sh.name, "text": " ".join(text.split()),
                           "box": box})
            continue
        # A connector carries its own direction through flipH / flipV; a plain
        # line autoshape is the box diagonal. Reading the flips is what stops
        # every line being read as top-left to bottom-right.
        flip_h = flip_v = False
        try:
            xfrm = sh._element.spPr.xfrm                # noqa: SLF001
            flip_h = bool(xfrm is not None and xfrm.get("flipH") == "1")
            flip_v = bool(xfrm is not None and xfrm.get("flipV") == "1")
        except AttributeError:
            pass
        if wid == 0 and hgt == 0:
            continue
        x0 = box[2] if flip_h else box[0]
        x1 = box[0] if flip_h else box[2]
        y0 = box[3] if flip_v else box[1]
        y1 = box[1] if flip_v else box[3]
        lines.append({"name": sh.name, "p0": (x0, y0), "p1": (x1, y1)})
    return {"labels": labels, "lines": lines}


def geometry(path: str, number: int | None = None,
             supplementary: bool = False) -> dict:
    """Every drawn source in this project, or one figure's, checked for
    collisions between its own elements.

    Reports `ok`, `collisions`, and - when python-pptx is not installed -
    `ran: false` with the reason. It never reports a clean slide it could not
    read.
    """
    out: dict = {"path": os.path.abspath(path), "ran": True, "note": "",
                 "sources": [], "collisions": [], "ok": True}
    # Asked rather than imported. The import itself happens in
    # `_slide_elements`, where it is used; importing here only to find out
    # whether it exists is the unused import a linter is right about.
    if importlib.util.find_spec("pptx") is None:
        out["ran"] = False
        out["note"] = ("python-pptx is not installed, so the slide's own "
                       "geometry was NOT checked. `pip install python-pptx`. "
                       "This is DID NOT RUN, not a clean result.")
        return out

    for f in list_float_dirs(path):
        if number is not None and not (f["n"] == number
                                       and f["supplementary"] == supplementary
                                       and f["kind"] == "figure"):
            continue
        for src in sources_in(f["path"]):
            full = os.path.join(f["path"], src)
            try:
                el = _slide_elements(full)
            except Exception as exc:
                out["sources"].append({"source": os.path.join(f["rel"], src),
                                       "read": False, "why": str(exc),
                                       "labels": 0, "lines": 0})
                out["ran"] = False
                out["note"] = ("at least one source could not be read, so "
                               "this is not a clean result")
                continue
            labels, lines = el["labels"], el["lines"]
            out["sources"].append({"source": os.path.join(f["rel"], src),
                                   "read": True, "why": "",
                                   "labels": len(labels), "lines": len(lines)})

            # --- a leader line through somebody else's label --------------
            for ln in lines:
                own = set()
                for i, lab in enumerate(labels):
                    grown = _shrink(lab["box"], -0.25)
                    for pt in (ln["p0"], ln["p1"]):
                        if (grown[0] <= pt[0] <= grown[2]
                                and grown[1] <= pt[1] <= grown[3]):
                            own.add(i)
                for i, lab in enumerate(labels):
                    if i in own:
                        continue
                    if _seg_hits_box(ln["p0"], ln["p1"], _shrink(lab["box"])):
                        out["collisions"].append({
                            "source": os.path.join(f["rel"], src),
                            "kind": "leader_through_label",
                            "a": ln["name"],
                            "b": "%s (%s)" % (lab["name"], lab["text"][:40]),
                            "detail": ("a leader line runs through the words "
                                       "of a label it does not belong to")})

            # --- two labels on top of each other --------------------------
            for i in range(len(labels)):
                for j in range(i + 1, len(labels)):
                    frac = _overlap_fraction(_shrink(labels[i]["box"]),
                                             _shrink(labels[j]["box"]))
                    if frac > OVERLAP_TOLERANCE:
                        out["collisions"].append({
                            "source": os.path.join(f["rel"], src),
                            "kind": "labels_overlap",
                            "a": "%s (%s)" % (labels[i]["name"],
                                              labels[i]["text"][:40]),
                            "b": "%s (%s)" % (labels[j]["name"],
                                              labels[j]["text"][:40]),
                            "detail": "%d%% of the smaller label is covered"
                                      % round(frac * 100)})
    out["ok"] = not out["collisions"]
    return out


def render(root: str, number: int | None = None, force: bool = False,
           supplementary: bool = False, timeout: int = 240,
           allow_overlap: bool = False) -> dict:
    """Render the panel sources without going through the whole R pipeline."""
    rs = _rscript()
    if not rs:
        return {"error": "Rscript not found on PATH or under C:/Program Files/R"}
    targets = []
    for f in list_float_dirs(root):
        if number is not None and not (f["n"] == number
                                       and f["supplementary"] == supplementary
                                       and f["kind"] == "figure"):
            continue
        if sources_in(f["path"]):
            targets.append(f)
    if not targets:
        return {"error": "no float folder here holds a *_source.pptx"}

    # Item 103, and it runs BEFORE the render rather than after it. A .png
    # that exists is a .png something composes into the manuscript, and the
    # staleness record written beside it says the panel is current. Refusing
    # afterwards would leave both on disk.
    geo = geometry(root, number, supplementary)
    if geo["collisions"] and not allow_overlap:
        return {"path": os.path.abspath(root), "rendered": [], "ok": False,
                "geometry": geo,
                "error": ("%d collision(s) in the drawing itself - nothing "
                          "was rendered. A line through a word renders "
                          "perfectly and is unreadable, so this refuses "
                          "rather than writing it. `--allow-overlap` "
                          "overrides, and says so in the result."
                          % len(geo["collisions"]))}

    done = []
    for f in targets:
        script = os.path.join(f["path"], PANELS_SCRIPT)
        if not os.path.isfile(script):
            write_panels_script(f["path"])
        # Sourced through setup.R exactly as render_all.R would, and with the
        # float context set the same way - so a render driven from here and a
        # render driven from the pipeline cannot behave differently.
        code = (f'source(here::here("plan","setup.R"));'
                f'set_float_context({_r_str(f["path"])}, {_r_str(f["label"])});'
                f'render_panel_sources(force={"TRUE" if force else "FALSE"})')
        p = subprocess.run([rs, "-e", code], cwd=root, capture_output=True,
                           text=True, encoding="utf-8", errors="replace",
                           timeout=timeout)
        out = (p.stdout or "") + (p.stderr or "")
        done.append({"label": f["label"], "dir": f["rel"],
                     "ok": p.returncode == 0, "output": out.strip(),
                     "sources": [source_state(f["path"], s)
                                 for s in sources_in(f["path"])]})
    return {"path": os.path.abspath(root), "rendered": done,
            "geometry": geo,
            "ok": all(d["ok"] for d in done)}


def _r_str(s: str) -> str:
    return '"' + s.replace("\\", "/").replace('"', '\\"') + '"'


# ---------------------------------------------------------------------------
# Text output
# ---------------------------------------------------------------------------

def print_status(res: dict) -> None:
    if not res["floats"]:
        print("No PowerPoint panel art in this project yet.")
        print("  add some with: python tools/graphic_figure.py add "
              "<project> --figure 1 --panel A")
        return
    for fl in res["floats"]:
        print(f"{fl['label']:<12} {fl['dir']}")
        if not fl["has_panels_script"]:
            print(f"    no {PANELS_SCRIPT} - re-run `add` to write one")
        for s in fl["sources"]:
            if not s["rendered"]:
                state = "NOT RENDERED"
            elif s["stale"]:
                state = "STALE - the .pptx has changed"
            else:
                px = "x".join(str(v) for v in s["px"]) if s["px"] else ""
                state = f"current  {px}  via {s['backend']}"
            label = f"panel {s['panel']}" if s["panel"] else "whole figure"
            print(f"    {label:<14} {s['source']:<24} {state}")
    print()
    if res["backend"]:
        print(f"render backend on this machine: {res['backend']}")
    else:
        print("NO RENDER BACKEND on this machine - neither PowerPoint nor")
        print("  LibreOffice. Export each slide by hand (File > Save As, PNG)")
        print("  next to its .pptx; everything downstream is identical.")
    if res["stale"]:
        print(f"{res['stale']} source(s) need re-rendering: "
              f"Rscript plan/render_all.R")


def print_add(res: dict) -> None:
    if res.get("error"):
        print(res["error"])
        return
    verb = "Would create" if res["dry_run"] else "Created"
    print(f"{verb} {res['pptx']}")
    print(f"  {res['width_in']} x {res['height_in']} in  (the pixel size is "
          f"set at render time, from the journal's dpi)")
    print(f"  {res['panels_script']}   renders it, and render_all.R runs that "
          f"before figure.R")
    if res["figure_written"]:
        print(f"  {res['dir']}/figure.R   written to compose it "
              f"(the slot was still empty)")
    else:
        print(f"  {res['dir']}/figure.R   left alone - add this line yourself:")
        for line in res["compose_line"].splitlines():
            print(f"      {line}")
    print()
    print("Next:")
    print(f"  1. open {res['pptx']} in PowerPoint and draw the panel")
    print( "     (the slide is already the right size - do not resize it)")
    print( "  2. Rscript plan/render_all.R")
    print( "  3. open plan/preview.html")


def print_geometry(res: dict) -> None:
    if not res["ran"]:
        print("DID NOT RUN: " + res["note"])
        if not res["sources"]:
            return
    n = sum(1 for x in res["sources"] if x["read"])
    print(f"{res['path']}")
    print(f"  {n} drawn source(s) read")
    for x in res["sources"]:
        if not x["read"]:
            print(f"  COULD NOT READ  {x['source']}: {x['why']}")
            continue
        print(f"  {x['source']:<44} {x['labels']:>3} labels "
              f"{x['lines']:>3} lines")
    if not res["collisions"]:
        if res["ran"]:
            print("\nNo element collides with another. This is a statement "
                  "about geometry")
            print("only - it says nothing about whether the figure shows what "
                  "the caption claims.")
        return
    print(f"\n{len(res['collisions'])} COLLISION(S) - the drawing overlaps "
          f"itself:")
    for c in res["collisions"]:
        print(f"\n  {c['source']}  [{c['kind']}]")
        print(f"    {c['a']}")
        print(f"    {c['b']}")
        print(f"    {c['detail']}")
    print("\nA line through a word renders perfectly and is unreadable. "
          "Move one of the two")
    print("in PowerPoint, or pass --allow-overlap if this is deliberate.")


def print_render(res: dict) -> None:
    if res.get("error"):
        print(res["error"])
        return
    for d in res["rendered"]:
        print(f"{d['label']:<12} {d['dir']}  {'ok' if d['ok'] else 'FAILED'}")
        for line in (d["output"] or "").splitlines():
            if line.strip():
                print(f"    {line}")
        for s in d["sources"]:
            mark = "stale" if s["stale"] else "current"
            print(f"    {s['source']:<24} {mark}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    p = argparse.ArgumentParser(prog="graphic_figure.py", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--json", action="store_true")

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--json", action="store_true",
                        default=argparse.SUPPRESS)

    sub = p.add_subparsers(dest="cmd", required=True)

    st = sub.add_parser("status", parents=[common],
                        help="every PowerPoint panel, and which renders are stale")
    st.add_argument("path")

    ad = sub.add_parser("add", parents=[common],
                        help="add a PowerPoint panel source to a figure folder")
    ad.add_argument("path")
    ad.add_argument("--figure", type=int, required=True,
                    help="the figure number, as in plan/figures/Fig02/")
    ad.add_argument("--panel", default="",
                    help="panel letter (A, B, ...); omit for a figure that is "
                         "one graphic with no panels")
    ad.add_argument("--supplementary", action="store_true")
    ad.add_argument("--width", default="single",
                    help="single | double | half | inches (default single)")
    ad.add_argument("--aspect", type=float, default=DEFAULT_ASPECT,
                    help="height / width (default 0.75)")
    ad.add_argument("--dry-run", action="store_true")

    rn = sub.add_parser("render", parents=[common],
                        help="render the panel sources without a full pipeline run")
    rn.add_argument("path")
    rn.add_argument("--figure", type=int, default=None)
    rn.add_argument("--supplementary", action="store_true")
    rn.add_argument("--force", action="store_true",
                    help="re-render even when the .pptx has not changed")
    rn.add_argument("--allow-overlap", action="store_true",
                    help="render even though elements of the drawing collide "
                         "(item 103). The override is recorded in the result")

    gm = sub.add_parser("geometry", parents=[common],
                        help="does the drawing collide with itself - a leader "
                             "line through a label, two labels on top of each "
                             "other (item 103)")
    gm.add_argument("path")
    gm.add_argument("--figure", type=int, default=None)
    gm.add_argument("--supplementary", action="store_true")

    args = p.parse_args()
    if not os.path.isdir(args.path):
        print(f"No such directory: {args.path}", file=sys.stderr)
        return 1

    if args.cmd == "status":
        res, printer = status(args.path), print_status
    elif args.cmd == "add":
        res = add(args.path, args.figure, panel=args.panel, width=args.width,
                  aspect=args.aspect, supplementary=args.supplementary,
                  dry_run=args.dry_run)
        printer = print_add
    elif args.cmd == "geometry":
        res = geometry(args.path, args.figure,
                       supplementary=args.supplementary)
        printer = print_geometry
    else:
        res = render(args.path, args.figure, force=args.force,
                     supplementary=args.supplementary,
                     allow_overlap=args.allow_overlap)
        printer = print_render

    if getattr(args, "json", False):
        print(json.dumps(res, indent=2, ensure_ascii=False))
    else:
        printer(res)
    if res.get("error"):
        return 1
    # A collision is a finding, and a finding exits 1 - the convention every
    # engine here follows. A check that could not run exits 2, because
    # "refused or unusable input" is what an absent python-pptx is, and
    # because 0 would be this command reporting a clean slide it never read.
    if args.cmd == "geometry":
        if not res.get("ran"):
            return 2
        return 1 if res.get("collisions") else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
